/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthPendingRouteImport } from './routes/auth.pending'
import { Route as AuthenticatedDonorDashboardRouteImport } from './routes/_authenticated/donor.dashboard'
import { Route as AuthenticatedDonorDonateRouteImport } from './routes/_authenticated/donor.donate'
import { Route as AuthenticatedDonorHistoryRouteImport } from './routes/_authenticated/donor.history'
import { Route as AuthenticatedDonorStatusRouteImport } from './routes/_authenticated/donor.status'
import { Route as AuthenticatedReceiverAcceptedRouteImport } from './routes/_authenticated/receiver.accepted'
import { Route as AuthenticatedReceiverDashboardRouteImport } from './routes/_authenticated/receiver.dashboard'
import { Route as AuthenticatedReceiverDiscoverRouteImport } from './routes/_authenticated/receiver.discover'
import { Route as AuthenticatedReceiverHistoryRouteImport } from './routes/_authenticated/receiver.history'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth.register.index'
import { Route as AuthRegisterDonorRouteImport } from './routes/auth.register.donor'
import { Route as AuthRegisterReceiverRouteImport } from './routes/auth.register.receiver'
import { Route as AuthenticatedDonorDonationIdRouteImport } from './routes/_authenticated/donor.donation.$id'
import { Route as AuthenticatedReceiverPickupIdRouteImport } from './routes/_authenticated/receiver.pickup.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingRoute = AuthPendingRouteImport.update({
  id: '/auth/pending',
  path: '/auth/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDonorDashboardRoute =
  AuthenticatedDonorDashboardRouteImport.update({
    id: '/donor/dashboard',
    path: '/donor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDonorDonateRoute =
  AuthenticatedDonorDonateRouteImport.update({
    id: '/donor/donate',
    path: '/donor/donate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDonorHistoryRoute =
  AuthenticatedDonorHistoryRouteImport.update({
    id: '/donor/history',
    path: '/donor/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDonorStatusRoute =
  AuthenticatedDonorStatusRouteImport.update({
    id: '/donor/status',
    path: '/donor/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiverAcceptedRoute =
  AuthenticatedReceiverAcceptedRouteImport.update({
    id: '/receiver/accepted',
    path: '/receiver/accepted',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiverDashboardRoute =
  AuthenticatedReceiverDashboardRouteImport.update({
    id: '/receiver/dashboard',
    path: '/receiver/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiverDiscoverRoute =
  AuthenticatedReceiverDiscoverRouteImport.update({
    id: '/receiver/discover',
    path: '/receiver/discover',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiverHistoryRoute =
  AuthenticatedReceiverHistoryRouteImport.update({
    id: '/receiver/history',
    path: '/receiver/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterDonorRoute = AuthRegisterDonorRouteImport.update({
  id: '/auth/register/donor',
  path: '/auth/register/donor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterReceiverRoute = AuthRegisterReceiverRouteImport.update({
  id: '/auth/register/receiver',
  path: '/auth/register/receiver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDonorDonationIdRoute =
  AuthenticatedDonorDonationIdRouteImport.update({
    id: '/donor/donation/$id',
    path: '/donor/donation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiverPickupIdRoute =
  AuthenticatedReceiverPickupIdRouteImport.update({
    id: '/receiver/pickup/$id',
    path: '/receiver/pickup/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/account': typeof AuthenticatedAccountRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending': typeof AuthPendingRoute
  '/donor/dashboard': typeof AuthenticatedDonorDashboardRoute
  '/donor/donate': typeof AuthenticatedDonorDonateRoute
  '/donor/history': typeof AuthenticatedDonorHistoryRoute
  '/donor/status': typeof AuthenticatedDonorStatusRoute
  '/receiver/accepted': typeof AuthenticatedReceiverAcceptedRoute
  '/receiver/dashboard': typeof AuthenticatedReceiverDashboardRoute
  '/receiver/discover': typeof AuthenticatedReceiverDiscoverRoute
  '/receiver/history': typeof AuthenticatedReceiverHistoryRoute
  '/auth/register/donor': typeof AuthRegisterDonorRoute
  '/auth/register/receiver': typeof AuthRegisterReceiverRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/donor/donation/$id': typeof AuthenticatedDonorDonationIdRoute
  '/receiver/pickup/$id': typeof AuthenticatedReceiverPickupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/account': typeof AuthenticatedAccountRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending': typeof AuthPendingRoute
  '/donor/dashboard': typeof AuthenticatedDonorDashboardRoute
  '/donor/donate': typeof AuthenticatedDonorDonateRoute
  '/donor/history': typeof AuthenticatedDonorHistoryRoute
  '/donor/status': typeof AuthenticatedDonorStatusRoute
  '/receiver/accepted': typeof AuthenticatedReceiverAcceptedRoute
  '/receiver/dashboard': typeof AuthenticatedReceiverDashboardRoute
  '/receiver/discover': typeof AuthenticatedReceiverDiscoverRoute
  '/receiver/history': typeof AuthenticatedReceiverHistoryRoute
  '/auth/register/donor': typeof AuthRegisterDonorRoute
  '/auth/register/receiver': typeof AuthRegisterReceiverRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/donor/donation/$id': typeof AuthenticatedDonorDonationIdRoute
  '/receiver/pickup/$id': typeof AuthenticatedReceiverPickupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending': typeof AuthPendingRoute
  '/_authenticated/donor/dashboard': typeof AuthenticatedDonorDashboardRoute
  '/_authenticated/donor/donate': typeof AuthenticatedDonorDonateRoute
  '/_authenticated/donor/history': typeof AuthenticatedDonorHistoryRoute
  '/_authenticated/donor/status': typeof AuthenticatedDonorStatusRoute
  '/_authenticated/receiver/accepted': typeof AuthenticatedReceiverAcceptedRoute
  '/_authenticated/receiver/dashboard': typeof AuthenticatedReceiverDashboardRoute
  '/_authenticated/receiver/discover': typeof AuthenticatedReceiverDiscoverRoute
  '/_authenticated/receiver/history': typeof AuthenticatedReceiverHistoryRoute
  '/auth/register/donor': typeof AuthRegisterDonorRoute
  '/auth/register/receiver': typeof AuthRegisterReceiverRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/donor/donation/$id': typeof AuthenticatedDonorDonationIdRoute
  '/_authenticated/receiver/pickup/$id': typeof AuthenticatedReceiverPickupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/account'
    | '/settings'
    | '/auth/login'
    | '/auth/pending'
    | '/donor/dashboard'
    | '/donor/donate'
    | '/donor/history'
    | '/donor/status'
    | '/receiver/accepted'
    | '/receiver/dashboard'
    | '/receiver/discover'
    | '/receiver/history'
    | '/auth/register/donor'
    | '/auth/register/receiver'
    | '/auth/register/'
    | '/donor/donation/$id'
    | '/receiver/pickup/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/account'
    | '/settings'
    | '/auth/login'
    | '/auth/pending'
    | '/donor/dashboard'
    | '/donor/donate'
    | '/donor/history'
    | '/donor/status'
    | '/receiver/accepted'
    | '/receiver/dashboard'
    | '/receiver/discover'
    | '/receiver/history'
    | '/auth/register/donor'
    | '/auth/register/receiver'
    | '/auth/register'
    | '/donor/donation/$id'
    | '/receiver/pickup/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/help'
    | '/_authenticated/account'
    | '/_authenticated/settings'
    | '/auth/login'
    | '/auth/pending'
    | '/_authenticated/donor/dashboard'
    | '/_authenticated/donor/donate'
    | '/_authenticated/donor/history'
    | '/_authenticated/donor/status'
    | '/_authenticated/receiver/accepted'
    | '/_authenticated/receiver/dashboard'
    | '/_authenticated/receiver/discover'
    | '/_authenticated/receiver/history'
    | '/auth/register/donor'
    | '/auth/register/receiver'
    | '/auth/register/'
    | '/_authenticated/donor/donation/$id'
    | '/_authenticated/receiver/pickup/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HelpRoute: typeof HelpRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPendingRoute: typeof AuthPendingRoute
  AuthRegisterDonorRoute: typeof AuthRegisterDonorRoute
  AuthRegisterReceiverRoute: typeof AuthRegisterReceiverRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pending': {
      id: '/auth/pending'
      path: '/auth/pending'
      fullPath: '/auth/pending'
      preLoaderRoute: typeof AuthPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donor/dashboard': {
      id: '/_authenticated/donor/dashboard'
      path: '/donor/dashboard'
      fullPath: '/donor/dashboard'
      preLoaderRoute: typeof AuthenticatedDonorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donor/donate': {
      id: '/_authenticated/donor/donate'
      path: '/donor/donate'
      fullPath: '/donor/donate'
      preLoaderRoute: typeof AuthenticatedDonorDonateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donor/history': {
      id: '/_authenticated/donor/history'
      path: '/donor/history'
      fullPath: '/donor/history'
      preLoaderRoute: typeof AuthenticatedDonorHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donor/status': {
      id: '/_authenticated/donor/status'
      path: '/donor/status'
      fullPath: '/donor/status'
      preLoaderRoute: typeof AuthenticatedDonorStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receiver/accepted': {
      id: '/_authenticated/receiver/accepted'
      path: '/receiver/accepted'
      fullPath: '/receiver/accepted'
      preLoaderRoute: typeof AuthenticatedReceiverAcceptedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receiver/dashboard': {
      id: '/_authenticated/receiver/dashboard'
      path: '/receiver/dashboard'
      fullPath: '/receiver/dashboard'
      preLoaderRoute: typeof AuthenticatedReceiverDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receiver/discover': {
      id: '/_authenticated/receiver/discover'
      path: '/receiver/discover'
      fullPath: '/receiver/discover'
      preLoaderRoute: typeof AuthenticatedReceiverDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receiver/history': {
      id: '/_authenticated/receiver/history'
      path: '/receiver/history'
      fullPath: '/receiver/history'
      preLoaderRoute: typeof AuthenticatedReceiverHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/donor': {
      id: '/auth/register/donor'
      path: '/auth/register/donor'
      fullPath: '/auth/register/donor'
      preLoaderRoute: typeof AuthRegisterDonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/receiver': {
      id: '/auth/register/receiver'
      path: '/auth/register/receiver'
      fullPath: '/auth/register/receiver'
      preLoaderRoute: typeof AuthRegisterReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donor/donation/$id': {
      id: '/_authenticated/donor/donation/$id'
      path: '/donor/donation/$id'
      fullPath: '/donor/donation/$id'
      preLoaderRoute: typeof AuthenticatedDonorDonationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receiver/pickup/$id': {
      id: '/_authenticated/receiver/pickup/$id'
      path: '/receiver/pickup/$id'
      fullPath: '/receiver/pickup/$id'
      preLoaderRoute: typeof AuthenticatedReceiverPickupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDonorDashboardRoute: typeof AuthenticatedDonorDashboardRoute
  AuthenticatedDonorDonateRoute: typeof AuthenticatedDonorDonateRoute
  AuthenticatedDonorHistoryRoute: typeof AuthenticatedDonorHistoryRoute
  AuthenticatedDonorStatusRoute: typeof AuthenticatedDonorStatusRoute
  AuthenticatedReceiverAcceptedRoute: typeof AuthenticatedReceiverAcceptedRoute
  AuthenticatedReceiverDashboardRoute: typeof AuthenticatedReceiverDashboardRoute
  AuthenticatedReceiverDiscoverRoute: typeof AuthenticatedReceiverDiscoverRoute
  AuthenticatedReceiverHistoryRoute: typeof AuthenticatedReceiverHistoryRoute
  AuthenticatedDonorDonationIdRoute: typeof AuthenticatedDonorDonationIdRoute
  AuthenticatedReceiverPickupIdRoute: typeof AuthenticatedReceiverPickupIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDonorDashboardRoute: AuthenticatedDonorDashboardRoute,
  AuthenticatedDonorDonateRoute: AuthenticatedDonorDonateRoute,
  AuthenticatedDonorHistoryRoute: AuthenticatedDonorHistoryRoute,
  AuthenticatedDonorStatusRoute: AuthenticatedDonorStatusRoute,
  AuthenticatedReceiverAcceptedRoute: AuthenticatedReceiverAcceptedRoute,
  AuthenticatedReceiverDashboardRoute: AuthenticatedReceiverDashboardRoute,
  AuthenticatedReceiverDiscoverRoute: AuthenticatedReceiverDiscoverRoute,
  AuthenticatedReceiverHistoryRoute: AuthenticatedReceiverHistoryRoute,
  AuthenticatedDonorDonationIdRoute: AuthenticatedDonorDonationIdRoute,
  AuthenticatedReceiverPickupIdRoute: AuthenticatedReceiverPickupIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HelpRoute: HelpRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPendingRoute: AuthPendingRoute,
  AuthRegisterDonorRoute: AuthRegisterDonorRoute,
  AuthRegisterReceiverRoute: AuthRegisterReceiverRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
